# Generated by Django 3.2.7 on 2021-09-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('clave_acceso', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('ambiente', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13)),
                ('cliente', models.CharField(max_length=100)),
                ('cedula_ruc', models.CharField(max_length=13)),
                ('ruta', models.URLField(max_length=300)),
            ],
        ),
    ]
