# Generated by Django 3.2.7 on 2021-09-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='ruta_xml',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
