# Generated by Django 3.2.7 on 2021-09-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0003_auto_20210916_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentos',
            name='numero',
            field=models.CharField(default='', max_length=100),
        ),
    ]
